services:
  ai1:
    image: python:latest
    deploy:
      replicas: 2
    restart: always
    ports:
      - "3050:3000"
    volumes:
      - /Pure-Wood/AI 

  bd:
    image: mysql:latest
    deploy:
      replicas: 2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 129034kbs
      MYSQL_DATABASE: pure_wood
      MYSQL_USER: pure_wood
      MYSQL_PASSWORD: 129034kbs
    volumes:
      - ./../Database/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  webapp:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    deploy:
      replicas: 2

  api1:
    build:
      context: ../Api/src/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      replicas: 2

volumes:
  mysql_data: