services:
  ai:
    build:
      context: ../AI
      dockerfile: Dockerfile
    image: python:latest
    deploy:
      replicas: 2
    restart: always
    volumes:
      - /Pure-Wood/AI
    networks:
      - app-network

  db:
    image: mysql:latest
    deploy:
      replicas: 2
    environment:                                       # Passwords removed for security reasons
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - ./../Database/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  webapp:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    networks:
      - app-network

  api:
    build:
      context: ../Api/src/
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    networks:
      - app-network

  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ../html5up-stellar/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
      - webapp
      - ai
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge